### ISSUE TITLE
variable names starting with $

### ISSUE THREAD

**Issue by mmikeww** [Pulover/Eval#1]
Is there any particular reason why you chose to prefix the variables with `$` ? It's not like we're in PHP where that is required. And its not any normal AHK convention either.

The bigger issue is that it won't run on AHK v2:

> Variable names cannot start with a digit and cannot contain the following characters which were previously allowed: @ # $. Only letters, numbers, underscore and non-ASCII characters are allowed.

https://autohotkey.com/v2/v2-changes.htm

**Comment by Pulover** [comment]
I know this is not required, I've written enough scripts in AHK. :P
The reason for me to choose the prefix is because this function deals with global variables and I was trying to minimize the chances of having an internal variable named the same as an user variable. Exactly because it's not usual to name them with prefixes in AHK.

About compatibility with AHK v2, I can only say that this was written for v1.1 and I cannot guarantee it will work on v2 even if you rename the variables. It relies on Uberi's ExprEval that was written for v1.0.

**Comment by mmikeww** [comment]
It seems the only globals are those from Uberi's functions. Are your $variables global too and I'm just missing it?

**Comment by mmikeww** [comment]
I'm working through this and this is gonna be ALOT of work to get working for v2. Probably not worth it. Plus there would need to be changes because AHK v2 strings allow you to deref variables directly as in `MsgBox("here is a %var% inside a string")`

Such poor decisions by Uberi by originally using so much non-expression if syntax

**Comment by mmikeww** [comment]
I must've had a brain fart, because v2 already supports basic expression evaluation WITHIN strings already:

`MsgBox("%2**(4*-1+10)/Floor(-1.3)%")`

This Eval() func is not obsolete though, because it does a lot of other things, even beyond the scope of AHKs own allowable expressions

**Comment by Pulover** [comment]
> It seems the only globals are those from Uberi's functions. Are your $variables global too and I'm just missing it?

You're correct, but if I'm not mistaken a local variable would take precedence and overwrite the global or not affect it at all. I can't remember. Also, in my PMC project they are global. 

I'm sorry I cannot help you with this but I'm very busy and wouldn't have the time. Maybe I can update it some day. Feel free to suggest a PR if you have improved it.
